import Head from 'next/head'
import Header from "../components/Header"
import Feed from "../components/Feed"
export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram 2.0 by Peter Braun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Feed />

      {/*Modal*/}


    </div>
  )
}
